# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import facetime_media_pb2 as facetime__media__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in facetime_media_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FaceTimeMediaStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/facetimebridge.v1.FaceTimeMedia/Health',
                request_serializer=facetime__media__pb2.HealthRequest.SerializeToString,
                response_deserializer=facetime__media__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Control = channel.unary_unary(
                '/facetimebridge.v1.FaceTimeMedia/Control',
                request_serializer=facetime__media__pb2.ControlRequest.SerializeToString,
                response_deserializer=facetime__media__pb2.ControlResponse.FromString,
                _registered_method=True)
        self.WaitIncoming = channel.unary_stream(
                '/facetimebridge.v1.FaceTimeMedia/WaitIncoming',
                request_serializer=facetime__media__pb2.WaitIncomingRequest.SerializeToString,
                response_deserializer=facetime__media__pb2.CallEvent.FromString,
                _registered_method=True)
        self.Audio = channel.stream_stream(
                '/facetimebridge.v1.FaceTimeMedia/Audio',
                request_serializer=facetime__media__pb2.AudioPacket.SerializeToString,
                response_deserializer=facetime__media__pb2.AudioPacket.FromString,
                _registered_method=True)


class FaceTimeMediaServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Control(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitIncoming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Audio(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceTimeMediaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=facetime__media__pb2.HealthRequest.FromString,
                    response_serializer=facetime__media__pb2.HealthResponse.SerializeToString,
            ),
            'Control': grpc.unary_unary_rpc_method_handler(
                    servicer.Control,
                    request_deserializer=facetime__media__pb2.ControlRequest.FromString,
                    response_serializer=facetime__media__pb2.ControlResponse.SerializeToString,
            ),
            'WaitIncoming': grpc.unary_stream_rpc_method_handler(
                    servicer.WaitIncoming,
                    request_deserializer=facetime__media__pb2.WaitIncomingRequest.FromString,
                    response_serializer=facetime__media__pb2.CallEvent.SerializeToString,
            ),
            'Audio': grpc.stream_stream_rpc_method_handler(
                    servicer.Audio,
                    request_deserializer=facetime__media__pb2.AudioPacket.FromString,
                    response_serializer=facetime__media__pb2.AudioPacket.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'facetimebridge.v1.FaceTimeMedia', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('facetimebridge.v1.FaceTimeMedia', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaceTimeMedia:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facetimebridge.v1.FaceTimeMedia/Health',
            facetime__media__pb2.HealthRequest.SerializeToString,
            facetime__media__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Control(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facetimebridge.v1.FaceTimeMedia/Control',
            facetime__media__pb2.ControlRequest.SerializeToString,
            facetime__media__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitIncoming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/facetimebridge.v1.FaceTimeMedia/WaitIncoming',
            facetime__media__pb2.WaitIncomingRequest.SerializeToString,
            facetime__media__pb2.CallEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Audio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/facetimebridge.v1.FaceTimeMedia/Audio',
            facetime__media__pb2.AudioPacket.SerializeToString,
            facetime__media__pb2.AudioPacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
